name = "Curves"
version = "0.1.0"
defaultTargets = ["curves"]

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "doc-gen4"
scope = "leanprover-community"

[[lean_lib]]
name = "Curves"

[[lean_exe]]
name = "curves"
root = "Main"
